apiVersion: v1
kind: Service
metadata:
  name: tinyswallow-1-5-b
  namespace: default
spec:
  ports:
  - name: http-tinyswallow-1-5-b
    port: 80
    protocol: TCP
    targetPort: 8000
  # The label selector should match the deployment labels & it is useful for prefix caching feature
  selector:
    app: tinyswallow-1-5-b
  sessionAffinity: None
  type: ClusterIP